site_name: Anjan's Blog
site_url: https://anjannair.xyz/blog/
repo_url: https://github.com/anjannair/blog
theme:
  language: en
  name: material
  custom_dir: overrides
  font:
    text: Special Elite
  features:
    - navigation.top
  palette:
    - media: "(prefers-color-scheme: light)" 
      scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)" 
      scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/anjannair
      name: Anjan on Github
  generator: false
copyright: Copyright &copy; 2021 - 2030 Anjan Nair
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
      auto_title: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - meta

